24.times{|i|a=[]
    "ABDEGHILMNRSTWXY AEIOY EO DFHLMNRSTX AE O AEIMO DFNST O AI AIO AEIMOUY AEOU DEFHIMNPRSWXY AEI I E HIO AIO HMNPST EO IU AEO A".split[i].chars{|c|a<<"ABDEFGHIJKLMNOPQRSTUWXYZ"[i]+c}
    puts a*" "}
